export const clientPorto = [
    {
        image: '/images/rkb.png',
        name: 'Rumah Kurma Bandung',
        category: 'Makanan'
    },
    {
        image: '/images/dripsweet.png',
        name: 'Dripsweet Official',
        category: 'Makanan'
    }
]

export const clientLogo = [
    '/images/client/1.jpeg',
    '/images/client/2.JPG',
    '/images/client/3.JPG',
    '/images/client/5.JPG',
    '/images/client/6.JPG',
    '/images/client/7.JPG',
    '/images/client/8.JPG',
    '/images/client/9.JPG',
    '/images/client/10.jpg',
    '/images/client/11.PNG',
    '/images/client/12.PNG',
    '/images/client/13.PNG',
    '/images/client/14.PNG',
    '/images/client/15.PNG',
    '/images/client/16.PNG',
    '/images/client/17.PNG',
    '/images/client/18.PNG',
    '/images/client/19.PNG',
    '/images/client/20.PNG',
    '/images/client/21.PNG',
    '/images/client/22.PNG',
    '/images/client/23.PNG',
    '/images/client/24.PNG',
    '/images/client/25.PNG',
    '/images/client/26.PNG',
    '/images/client/27.PNG',
    '/images/client/28.PNG',
    '/images/client/29.PNG',
    '/images/client/30.PNG',
    '/images/client/31.PNG',
    '/images/client/32.PNG',
    '/images/client/33.PNG',
    '/images/client/34.PNG',
    '/images/client/35.PNG',
    '/images/client/36.PNG',
    '/images/client/37.PNG',
    '/images/client/38.PNG',
    '/images/client/39.PNG',
    '/images/client/40.PNG',
    '/images/client/41.PNG',
    '/images/client/42.PNG',
    '/images/client/43.PNG',
    '/images/client/44.PNG',
    '/images/client/45.PNG',
    '/images/client/46.PNG',
    '/images/client/47.PNG',
    '/images/client/48.PNG',
    '/images/client/49.PNG',
    '/images/client/50.PNG',
    '/images/client/51.PNG',
    '/images/client/52.PNG',
    '/images/client/53.jpeg',
    '/images/client/54.jpg',
    '/images/client/55.jpg',
    '/images/client/56.jpg',
]