export const clientPorto = [
    {
        image: '/images/rkb.png',
        name: 'Rumah Kurma Bandung',
        category: 'Makanan'
    },
    {
        image: '/images/dripsweet.png',
        name: 'Dripsweet Official',
        category: 'Makanan'
    }
]

export const clientLogo = [
    '/images/client/1.jpeg',
    '/images/client/2.jpg',
    '/images/client/3.jpg',
    '/images/client/5.jpg',
    '/images/client/6.jpg',
    '/images/client/7.jpg',
    '/images/client/8.jpg',
    '/images/client/9.jpg',
    '/images/client/10.jpg',
    '/images/client/11.png',
    '/images/client/12.png',
    '/images/client/13.png',
    '/images/client/14.png',
    '/images/client/15.png',
    '/images/client/16.png',
    '/images/client/17.png',
    '/images/client/18.png',
    '/images/client/19.png',
    '/images/client/20.png',
    '/images/client/21.png',
    '/images/client/22.png',
    '/images/client/23.png',
    '/images/client/24.png',
    '/images/client/25.png',
    '/images/client/26.png',
    '/images/client/27.png',
    '/images/client/28.png',
    '/images/client/29.png',
    '/images/client/30.png',
    '/images/client/31.png',
    '/images/client/32.png',
    '/images/client/33.png',
    '/images/client/34.png',
    '/images/client/35.png',
    '/images/client/36.png',
    '/images/client/37.png',
    '/images/client/38.png',
    '/images/client/39.png',
    '/images/client/40.png',
    '/images/client/41.png',
    '/images/client/42.png',
    '/images/client/43.png',
    '/images/client/44.png',
    '/images/client/45.png',
    '/images/client/46.png',
    '/images/client/47.png',
    '/images/client/48.png',
    '/images/client/49.png',
    '/images/client/50.png',
    '/images/client/51.png',
    '/images/client/52.png',
    '/images/client/53.jpeg',
    '/images/client/54.jpg',
    '/images/client/55.jpg',
    '/images/client/56.jpg',
]